# Generated by Django 2.2.9 on 2020-08-01 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0005_auto_20200731_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/profiles'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/posts'),
        ),
    ]
